---
title: "Predicting Spam Emails based on Word Frequencies"
author: "Octavio Lima, Zoë Arnaut, Cyrus Tadjiki"
output: 
  xaringan::moon_reader:
          css: [default, metropolis, metropolis-fonts] 
          lib_dir: libs
          nature:
            highlightStyle: github
            highlightLines: true 
            highlightSpans: true
            countIncrementalSlides: false
            keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
- Spam messages are annoying but also invasive

- An open spam email can transmit personal and computer information to a spammer, including:
  - your IP address
  - your location
  - your device type
  - your operating system
  - your place of work
  - and more...
  
- Email providers use machine algorithms to screen messages and protect their users, which is what we will be attempting to do

- **Research Question:** What type of model predicts spam emails using word frequencies the best?
 
---
 
# Data and Methods

 - We got data on [Kaggle](https://www.kaggle.com/venky73/spam-mails-dataset)
 - Text of 500 spam emails and 2,500 non-spam emails
 - Stemming (retrieving the root of a word)
 - Removing common stop words (such as “the” and “to”)
 
 
 - Show Word Cloud of spam and non-spam
 - Keep it short

 - Naive Bayes  
 - Lasso  
 - Logistic Lasso
 - Logistic
 - Random Forest
---

# Results
